
project_id = "bmkhbqxukiakhafqllux"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

# Enable the Edge Functions API
[functions]
port = 54324

# Add configuration for our validate-wireframe function
[functions.validate-wireframe]
verify_jwt = true
