
project_id = "bmkhbqxukiakhafqllux"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.generate-wireframe]
verify_jwt = true

[functions.admin-user-management]
verify_jwt = true

[functions.analyze-feedback]
verify_jwt = true

[functions.send-client-link]
verify_jwt = true
