
project_id = "bmkhbqxukiakhafqllux"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.notifications-api]
verify_jwt = true
[functions.generation-api]
verify_jwt = true

